### ISSUE TITLE
Wrong order of execution with VkEvent and VkSemaphore

### ISSUE THREAD

**Issue by Qining** [google/gapid#1293]
Example case:
```
vkQueueSubmit(Queue A)
  - vkCmdWaitEvents(Event E)
  - Signal Semaphore X

VkQueueSubmit(Queue B)
  - Wait for Semaphore X
  - vkCmdCopyImage ( Img1 -> Img0)

VkQueueSubmit(Queue C)
  - vkCmdCopyImage ( Img2 -> Img0)

VkQueueWaitIdle(Queue C)
...
vkSetEvent(Event E)
vkQueueWaitIdle(Queue B)
```

In reality, when the application hits `vkQueueWaitIdle(Queue B)` the `Img0` should contains the content of `Img1`. But in GAPID, the content will be `Img2`. The execution order should be 1) Img2->Img0, then 2) Img1->Img0, but in GAPID, the order is wrong.

This is because we didn't consider the cases where semaphore may be 'pending' (hence 'blocking') due to the use of VkEvent.

Even though VkEvent cannot be used on multiple queue, it actually still can block more than one VkQueue

**Comment by Qining** [comment]
This is also related to #1291 as sparse binding operation might be blocked by VkEvent then.

**Comment by AWoloszyn** [comment]
Strickly  speaking, I think that this specific example,  we would not be incorrect to show either the contents of Img1 or Img2 for Img1. This is only because we don't have a memory barrier in there, so the write visibility is not guaranteed between submissions. However this case can come up elsewhere, and the fix is good for both.
