### ISSUE TITLE
gapic: The 1:1 image zoom button is no longer sticky

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1425]
I implemented this so that the 1:1 mode would stick until you either zoomed or toggled the button.
This way, you don't have to zoom every time you changed textures.

This behavior appears to have been either broken or changed. Now it's a one-shot reset.

**Comment by ben-clayton** [comment]
Humm, I'm an idiot. It was actually the zoom-to-fit button that was sticky.

However, given that even I can't remember which one it was, perhaps both should be?

**Comment by pmuetschard** [comment]
zoom-to-actual does not need to be sticky, because it inherently is. The zoom level is maintained, and zoom-to-actual is just an alias for "zoom=1". Zoom-to-fit should be marked as sticky because it overrides the default zoom behavior. Zoom-to-actual doesn't.

However, if you feel that the zoom-to-actual button should have the same "toggle" behavior as the zoom-to-fit button, I could be convinced to do that...

**Comment by ben-clayton** [comment]
Well, it wasn't clear to me in my idiot state. The CL I've put up for review makes the UI clearer (to me), and I think the code is slightly cleaner (again IMHO).
