### ISSUE TITLE
Improve panic logging

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#144]
Proposal:
* Add a flag to the `GetLogStream` that disables the stdout & stderr `log.Handler` for the duration of the call.
* In GAPIC log all stdout & stderr lines to the standard logger.
* If the GAPIS process terminates unexpectedly, we can use the last N log entries in any bug report.

This avoids all the nasty string comparison logic and unifies the log handling.

**Comment by pmuetschard** [comment]
> Add a flag to the GetLogStream that disables the stdout & stderr log.Handler for the duration of the call.

I don't think this is really all that useful. GAPIC always launches gapis with a log file path, which looks like already has this side effect. Also, if GAPIS is running remotely it would be counter intuitive why it stops logging.

> In GAPIC log all stdout & stderr lines to the standard logger.

This is already happening. It's the only reason you can see any of GAPIS' output, when it panics.

> This avoids all the nasty string comparison logic

Are you talking about the 'panic dection' logic in GAPIC? I didn't know you disapproved of it that much. We can just remove it, it was only there to show the panic to the user when GAPIS crashes (instead of just saying, 'hey GAPIS crashed'). Since we have the log view now, we could completely remove it. Though, if we do create automatic bugs, we'd probably would want to automatically mark those with panics, since they have something very actionable to look at.

**Comment by ben-clayton** [comment]
> GAPIC always launches gapis with a log file path, which looks like already has this side effect.

Oh really? I should have checked.

> Are you talking about the 'panic dection' logic in GAPIC?

Yes, but I'm not _that_ opposed to it. I was just thinking about the crash reporting workflow. Panics are a subset of the cases we need to deal with.

Given that the first 2 cases are already done, I'm just going to close this as 'Reporter doesn't know what he's talking about'.
