### ISSUE TITLE
GAPID building with Bazel for Windows

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1515]
* [x] GAPIC
* [x] gapid.apk
* [x] GAPII
* [x] GAPIR
* [x] GAPIS
* [x] GAPIT
* [x] VirtualSwapchain layer
* [x] Stringtable

**Comment by pmuetschard** [comment]
Blocker at this point is that because our code-gen'ed protos are so large, the '-c opt' build fails unless it uses `-Wa,-mbig-obj`. Since this is a proto rule, the flag has to be specified globally, but cgo does not support reading big object files. To fix, either add support to golang for big object files, or split up the protos.

**Comment by ianthehat** [comment]
What is the cgo error?

**Comment by pmuetschard** [comment]
> What is the cgo error?

`foo.o: not an object file`

 See `cmd/link/internal/ld/lib.go`, which looks for magic bytes in the `.o` files.
