### ISSUE TITLE
request: Support for new Vulkan MacOS SDK?

### ISSUE THREAD

**Issue by oscarbg** [google/gapid#1674]
Note don’t know if makes much sense but now that Vulkan MacOS SDK has been released and the core Metal wrapper (MoltenVK) too (even open sourced), just asking if much work to support it? Or course right now we must use (I assume) Xcode Metal debug capabilities.. and of course after 1.0 release..
With new Vulkan version hopingly coming GDC, seems gapid still have a road ahead after 1.0..
Note posted exact same request on Renderdoc..

**Comment by ben-clayton** [comment]
Hi @oscarbg,

This is something we are definitely considering. If there's enough interest in supporting Vulkan trace and replay on macOS, we may adjust our priorities accordingly.

If this is something that is of interest to you, please feel free to let us know below.

Cheers,
Ben

**Comment by oscarbg** [comment]
no serious need right now, thanks..
just I want to start toying around with some experiments with Vulkan Macos and a Vulkan debugger seeems valuable to have..
let's keep open the issue for others to ask for support then..

**Comment by AWoloszyn** [comment]
Just to chime in, as long as the MoltenVK "loader" supports the same layer system as Vulkan on other platforms, this should actually be quite straight-forward. 

I think there might be some subtleties in how we handle getting pointers, since a system-level libvulkan.so is not guaranteed to exist, but they should be solvable.

The only other problem would be that our replay client would have to be built against a fixed version of MoltenVK, and so if a user had a different (incompatible) version, or a customized version, then the results may not match.

**Comment by oscarbg** [comment]
not really,
please take a look at the Vulkan Macos SDK: it has a also an early libvulkan.dylib and ICD model (a json file which points to libMoltenVK.dylib and instructions to copy json to /etc/vulkan/icd.d/drivers)..
of course we are early days there but if it will lower your work to do a quick port to test assume this model..
all I'm saying, is you can link to libMoltenVK directly also as you say and it will work but what GAPID  should really link to libvulkan.dylib on SDK that would avoid linking to a fixed version of MoltenVK as you say..

up to now all I'm talking is about Macos Vulkan..

as you know, SDK has also IOS support and yes you are correct on IOS there is no ICD model, no libvulkan.dylib so you must link to MoltenVK..
but even then I don't see a problem MoltenVK should have and ABI stable interface (i.e. only expose Vulkan API) and altough they expose new extensions Vulkan has a "get function pointer" feature for that case or I'm wrong?

**Comment by AWoloszyn** [comment]
Added!
