### ISSUE TITLE
Running gazelle trashes the BUILD.bazel files

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#2054]
What was:
`    importpath = "github.com/google/gapid/foo/bar"`
`    deps = ["//foo/bar:go_default_library"]`

now becomes:
`    importpath = "foo/bar"`
`    deps = ["//github.com/google/gapid/foo/bar:go_default_library"]`

For 206 files.

**Comment by ben-clayton** [comment]
Maybe this is the new way of doing things - but it's also worth mentioning that these changes do not build.

**Comment by ianthehat** [comment]
That looks wrong to me
@jayconrod might have some insight, it looks like it did not work out what the root path of the project was correctly...
were you still using the manual prefix method before?

**Comment by jayconrod** [comment]
It sounds like gazelle might be missing the Go prefix. How are you running Gazelle exactly? When I check out `master` and run `bazel run //:gazelle`, I see a few minor differences, but only in 4 files, not 206, and nothing related to `importpath`.

**Comment by ben-clayton** [comment]
I ran it (and always have) with `bazel run gazelle .`

Running it the way you suggest does the right thing. User error or is this change in behavior a bug?

**Comment by jayconrod** [comment]
I'd recommend running Gazelle either as `bazel run //:gazelle` (without arguments after the target name) or by adding a `# gazelle:prefix path` directive in the root build file (I'll send a PR for this shortly).

The `gazelle` rule builds a wrapper script that invokes Gazelle using pre-generated arguments. The current rule translates into `gazelle fix -go_prefix github.com/google/gapid`. If you pass additional arguments to `bazel run`, those replace the pre-generated arguments. That lets you invoke other Gazelle commands like `bazel run //:gazelle update-repos example.com/new/dep`. So passing the additional `.` means Gazelle *won't* receive the `-go_prefix` argument, which it needs to generate the import paths.

Earlier, Gazelle was not getting the `-go_prefix` argument, but it was reading the prefix from the `go_prefix` rule. That was removed in 80b8f086 because `go_prefix` was deprecated and removed in rules_go.

You might wonder why Gazelle doesn't read the `prefix` attribute from the `gazelle` rule instead. We now have a more uniform method of configuration: directives. Most configuration options can be set with comments in build files like this:

```
# gazelle:prefix github.com/google/gapid
```

This is now the best way to set the prefix. It can be done in any directory (it applies to subdirectories), and Gazelle will read it, regardless of arguments.

**Comment by pmuetschard** [comment]
@ben-clayton assuming you are at the root, you can just run `bazel run gazelle`

@jayconrod comments with magical meaning don't sound like a better way than an attribute in a rule to me. Is it not possible to append additional command line arguments, instead of replacing the ones produced by the attributes?

**Comment by jayconrod** [comment]
@pmuetschard Attributes in the `gazelle` rule correspond pretty directly to command-line arguments. Command-line arguments are not expressive enough as a configuration mechanism. For example, if you want to set different Go prefixes or proto rule generation modes in different directories, directives let you do that in situ. It would be unwieldy to specify that on the command line.

About appending command line arguments, that opens one door but closes another. I think it's important to be able to run alternate commands like `update-repos` by replacing pre-generated arguments.
