### ISSUE TITLE
How gapis code is parsing gfxtrace file into required data for showcasing in UI ?

### ISSUE THREAD

**Issue by gittmi** [google/gapid#2154]
Hi,
    Is there any design/architecture document for gapid tool code? I am trying to understand the gapis part. 
    There are many directories like api, capture, database, memory, messages, replay, resolve etc. 
        Once the trace file is imported, it is directly stored into database. 
   
If the data is put directly in the format that we want for later reply, What is the role of resolve,memory, cmd.go, mesh.go, state.go etc files? 

It would be great if you provide some pointers in this regard.

**Comment by AWoloszyn** [comment]
https://github.com/google/gapid/blob/master/gapis/README.md has some of this information. But GAPIS provides more than simply replaying the command stream. Most of the files you pointed to are about providing semantic information about the trace.

For example: mesh.go is responsible for interpreting draw calls and providing the mesh view in the UI,This is independent from replay, (and we provide this regardless of if you are actually replaying data).

The same is true of state/cmd/memory. These are (mostly) used to provide relevant information to the UI. state.go is used to expose information about the state tree. We can provide information about the state at a particular time, without having to go over to a replay device and query it.

Lastly the format of the data put in the database when we import a capture is not the format we use for replay. The replay tool (cmd/gapir/*) is a simple VM that interprets instructions. GAPIS generates lists of these instructions for replay. Sometimes we replay the original trace unaltered (eg. for the report view) but sometimes we modify the commands passed to the replay in order to get more information (actually getting screenshots requires that we pull back data from the device).

https://github.com/google/gapid/blob/master/gapis/replay/asm/instructions.go describes the instructions that are passed to the replay client.

The actual instructions come from the generated mutate.go files (e.g. `bazel-genfiles/gapis/api/vulkan/mutate.go`) which is where the bulk of the functionality of GAPID lives.
