### ISSUE TITLE
Contribution to API statistics feature

### ISSUE THREAD

**Issue by gittmi** [google/gapid#2266]
Hi,
We want to implement API statistics feature into gapid tool. I realized this feature is in your future list and development is going on actively. I would like to contribute in developing the feature so that, I can get better understanding of code and contribute further.

What is the approach in contributing the development of this feature? Does working on bugs/issues if any, related to this feature will help? How can I identify issues specific to this feature?

Thanks.

**Comment by ben-clayton** [comment]
Hi @gittmi,

Sorry for the slow reply, and thank you for your interest in contributing to GAPID.

To help steer you in the right direction, are you able to describe in more detail the sorts of statistics you want to add?

Many thanks,
Ben

**Comment by gittmi** [comment]
Hi Ben,
The description of the feature that i want to implement is as below,
    * Tool user should know, how many different APIs have been called per frame (list of APIs)
    * Tool user should know, how many times an API has been called per frame (number of times it has been called in a frame), this idea is to show the API name along with call count

And I believe that this will help the user / developer in optimizing the API calls, that were called many number of times.

In addition to this, I also want to showcase the number of draw calls that are called per frame and number of vertices per draw call etc.,

And another feature is to showcase the time taken by the APIs based on the timer. I am not sure whether this will give correct time or not.

Thanks,
Hithendra.

**Comment by ben-clayton** [comment]
Hi @gittmi,

Some of what you are trying to add has already been implemented as part of `gapit stats`. The code that actually does the evaluation [can be found here](https://github.com/google/gapid/blob/master/gapis/resolve/stats.go).

To give a high level overview of how all this works:

GAPIS is the server, which is the only executable that really knows about the graphics APIs. 
GAPIT and the UI are clients that make queries to GAPIS.

GAPIS and the client talk via [gRPC](https://grpc.io/). The interface is defined in the two proto files:
1. [gapis/service/service.proto](https://github.com/google/gapid/blob/master/gapis/service/service.proto)
2. [gapis/service/path/path.proto](https://github.com/google/gapid/blob/master/gapis/service/path/path.proto)

`service.proto` contains all the RPC functions. Some of these are fairly self explanatory, such as `GetDevices()`. However, there are two deceptively complicated functions, which are `Get()` and `Set()`.

Graphics trace files contain a lot of data that needs to be referenceable by the client, so that GAPIS can answer queries like "What's the framebuffer data of attachment X at command Y of capture Z?".

To allow the client to make these sorts of queries, we have the concept of 'paths' which are declared in `paths.proto`.
A path is a chain of nodes, which point to some bit of data in the capture.
For example, if the client wanted to reference the 'foo' parameter of command 30, it would create the path: `Capture<id:'capture-id'>.Command<id:30>.Parameter<name='foo'>`. This path is represented by the proto message:

```
Parameter {
    name: "foo",
    command: Command {
        indices: [30],
        capture: Capture {
            ID: "capture-id",
        }
    }
} 
```

Using this path, the client can call the `Get()` RPC to request the specified data. As a common pattern, we typically have the `Get()` function return a `service` proto message that shares the name of the `path` proto message.
For example, calling `Get()` with a `path.CommandTree` will return a `service.CommandTree`.

`Set()` as you might have guessed allows the client to make changes to the capture. Only a handful of the path types can be assigned to - command parameters are the most common `Set()` target. Note that if you call `Set()` to change a value in the capture, you are returned a path with a new `Capture` ID. This is because GAPIS is a multi-client service, and capture data is immutable.

All of the service RPC functions are directly implemented by [gapis/server/grpc.go](https://github.com/google/gapid/blob/master/gapis/server/grpc.go). These functions mostly translate the grpc function signatures to a more go-friendly interface declared in (gapis/service/service.go)[https://github.com/google/gapid/blob/master/gapis/service/service.go]. The reason for this interface is that it allows a go-client to talk directly to a go-server without actually having to go through gRPC - this is helpful for testing. The server interface is implemented in [gapis/server/server.go](https://github.com/google/gapid/blob/master/gapis/server/server.go), which contains the bulk of the real server function implementations.

The `Get()` and `Set()`s functions are handled by the [`gapis/resolve` package](https://github.com/google/gapid/tree/master/gapis/resolve). This package deals with untangling the path nodes, and resolving to the capture data. The `gapis/resolve` package also makes heavy use of the [database's `Resolveable`](https://github.com/google/gapid/blob/master/gapis/database/resolvable.go) functionality (hence the name), which is a system that allows data to be calculated and stored once for later lookup. I've added some details of this in a different issue (https://github.com/google/gapid/issues/2288).

So going back to the stats...

Calling the gRPC function `Get()` with a `path.Stats`, will cause GAPIS to execute the `resolve.Stats()` function (after writing all of this, I've noticed that `Stats` doesn't seem to be a resolvable - we should fix this). Some stat gathering is done, and the results are placed into a `service.Stats`, which is returned by the RPC.

If you want to add additional stat logic, then consider adding fields to the `path.Stats`.

---

> In addition to this, I also want to showcase the number of draw calls that are called per frame and number of vertices per draw call etc.

GAPIS deals with multiple graphics APIs, which can have very different definitions a 'frame', 'draw call' etc. We make a best-effort to abstract these groupings via [`Event`s](https://github.com/google/gapid/blob/master/gapis/resolve/events.go).
Events are used [to build the command tree](https://github.com/google/gapid/blob/master/gapis/resolve/command_tree.go), and by using events we can construct different command hierarchies based on parameters in the path (do you want to group by thread? context? frame? draw? etc).

The existing stats code currently just asks for all the `LastInFrame` events. Take a look at the `path.Events` message for other event types.

---

> And another feature is to showcase the time taken by the APIs based on the timer

Time taken where? At trace time or replay?

---

This is a lot of info, and I'm sure you'll have lots of questions. Sorry its taking me so long to reply - I've been doing a lot of traveling!

Cheers,
Ben

**Comment by gittmi** [comment]
Hi Ben,

Thanks for your pointers; it has really helped me in understanding the code architecture.

Our plan was to provide the API call statistics, i.e., for each frame, how many APIs have been called and how many times that each API has been called, and as per my understanding the current Spy / Call Observer functions does not give this kind of data.

So, I am planning to add a new spy function to hold this data per frame.

To call this spy function from interceptor APIs, template files need to be modified to generate the new intercepted APIs with newly added spy/observer call.

From the newly added spy function, we can write the call stats data into trace file by using a protobuf.

I feel this API call data of each API will let the developer know, which API was called many number of times and that API can be further optimized.

So do you think that it will add any advantage to the game developer in debugging? , because the current GAPID implementation doesn't contain this kind of API call statistics information.

> Time taken where? At trace time or replay?

I feel time taken at trace will be the actual time taken by the API than at replay time. But, at trace time we have to consider the intercepted call overhead also.

By using timer APIs can we achieve this?

Intercepted Graphics API ()
{
 startTime = startTimer()
 Actual driver API call()
 endTime = stopTimer()
}
time taken by API = endTime - startTime

Thanks,
Hithendra.

**Comment by ben-clayton** [comment]
> Our plan was to provide the API call statistics, i.e., for each frame, how many APIs have been called and how many times that each API has been called, and as per my understanding the current Spy / Call Observer functions does not give this kind of data.

It seems like these statistics could be calculated from the existing data in a `.gfxtrace` file?
If so, we prefer to keep logic out of the interceptor, as we do not want to add unnecessary overhead. I believe these counts could easily be added to [`gapis/resolve/stats.go`](https://github.com/google/gapid/blob/master/gapis/resolve/resolve.go). Is there something here that I'm missing that can only be calculated at trace time?

> So do you think that it will add any advantage to the game developer in debugging? , because the current GAPID implementation doesn't contain this kind of API call statistics information.

Yes! Number of draw call submissions, framebuffer switches, etc are all important data-points when trying to diagnose poor performance.

Timing the real driver calls may provide interesting numbers, so long as the user is aware that the interceptor overhead may skew results (for example, the additional gapii overhead will likely slow the CPU, and likely letting the GPU catch up). I'd expect many of these calls to be short with the occasional stall when the CPU has to synchronize with the GPU. Finding these stalls will still be valuable.

If you want to experiment adding these timings, you should take a look at [`gapis/api/templates/api_spy.cpp.tmpl`](https://github.com/google/gapid/blob/master/gapis/api/templates/api_spy.cpp.tmpl#L218), which generates the call to the real driver.

For encoding API-agnostic metadata like this, we add messages to the [`gapis/api/gfxtrace.proto`](https://github.com/google/gapid/blob/master/gapis/api/gfxtrace.proto) file. These messages can be encoded as a child of the call proto, which adds them as 'extras' to the command. `Extras` are additional metadata tagged on to a command, and can be accessed with the [`api.Cmd.Extras()`](https://github.com/google/gapid/blob/master/gapis/api/cmd.go#L57) accessor.

The [`CallObserver::observeTimestamp()`](https://github.com/google/gapid/blob/master/gapii/cc/call_observer.cpp#L111-L119) function is an example of an extra being encoded. 

Cheers,
Ben

**Comment by gittmi** [comment]
Hi Ben,
I got some doubt here. My understanding is that
https://github.com/google/gapid/blob/master/gapis/api/templates/api_spy.cpp.tmpl contains onPostDrawCall for all draw calls. onPostDrawCall() is a spy function in which we are maintaining and updating mNumDraws  & mNumDrawsPerFrame. This data eventually will be written to gfxtrace file. I didn't get where & how the data is being written to gfxtrace file. 

So, I thought we are actually calculating the drawcall stats from the spy function. 
From your comments, it seems this is not the way it is happening. 
In the https://github.com/google/gapid/blob/master/gapis/resolve/stats.go file we are getting all the commands from the capture and we are getting the events as below:
// Get the present calls
	events, err := Events(ctx, &path.Events{
		Capture:     capt,
		LastInFrame: true,
	}, r)

But, nowhere we filtered events related to draw calls specifically. Suppose if I want to get all API call info how can I get that? If I get event info for each and every API call made then I can have counter for each API(not resticted to draw calls) and show it to the developer. 

If we can get info about all APIs, we need not touch the interceptor part.
Is this understanding correct?  Please calrify.

**Comment by ben-clayton** [comment]
> onPostDrawCall() is a spy function in which we are maintaining and updating mNumDraws & mNumDrawsPerFrame

This does exist, yes, but not to write stats to the file. It is used to take periodic snapshots of the backbuffer if you trace with the `gapit trace -observe-draws` flag. I am not aware of anything that writes these counts directly to the `.gfxtrace` file - nor do I think we should, as this is information that can already be calculated offline.

> But, nowhere we filtered events related to draw calls specifically

You can [specify you want draw call events in the `path.Events` message](https://github.com/google/gapid/blob/master/gapis/service/path/path.proto#L155).
These events are not generated by metadata in the `.gfxtrace` file, but are generated by looping over the commands in the trace and looking at the flags associated with the [command type flags](https://github.com/google/gapid/blob/master/gapis/resolve/events.go#L157).
The `api.Cmd.CmdFlags()` function is generated and implemented by [gapis/api/templates/api.go.tmpl](https://github.com/google/gapid/blob/master/gapis/api/templates/api.go.tmpl#L1677-L1693), which uses annotations on the command definition in the `.api` file. See [gapis/api/gles/api/draw_commands.api](https://github.com/google/gapid/blob/master/gapis/api/gles/api/draw_commands.api#L57) for examples of these annotations.

**Comment by gittmi** [comment]
Thanks Ben. I am working on it.

**Comment by AWoloszyn** [comment]
Closing this now. Feel free to add comments, and I will re-open if this is still in progress.
