### ISSUE TITLE
Variable is only written into, never read

### ISSUE THREAD

**Issue by hevrard** [google/gapid#2729]
This variable is only write into:

https://github.com/google/gapid/blob/4f00997554b7d863349e0121ab03618785b81780/gapir/cc/cached_resource_loader.cpp#L68

Should revisit the logic and probably report as soon as there is a failure in loadCache

**Comment by AWoloszyn** [comment]
`mCache->loadCache` should never fail if `mCache->hasCache()` returns true, based on the code that I have read. We should probably assert here that it succeeds,  rather than accumulate results. (I am not sure what we should do it loadCache() returned false, there is no sensible recovery condition when the cache gets out of sync.
