### ISSUE TITLE
GLES context ID mismatch between UI and gapit

### ISSUE THREAD

**Issue by hevrard** [google/gapid#2847]
On a simple cube app trace, the GLES context ID (0 or 1) in the UI seems to be understood as the inverse of what `gapit commands -context <id>` does. E.g., selecting context 0 in the UI list the commands obtained by passing `-context 1` in gapit, and vice-versa.

**Comment by hevrard** [comment]
I would like to keep this one as a first time contribution opportunity.

**Comment by pmuetschard** [comment]
The UI shows the name of the context as provided by the server (i.e. the `name` field in the `service.Context` proto message), whereas gapit treats it as in index into the context list. The fact that the server calls them "GLES Context <n>" is just a coincidence. There are cases where we give the contexts different names though.

We should fix it so that
- the name matches the `context.Identifier` field
- gapit looks them up in the same way

We should probably add the identifier into the `service.Context` message.
