### ISSUE TITLE
Vulkan: vkCmdDrawIndexed not considered a draw call, does not show geometry drawn

### ISSUE THREAD

**Issue by ronaldfw** [google/gapid#2870]
When picking a vkCmdDrawIndexed call in the list of commands in a capture, the "Geometry" tab will just show "Select a draw call" instead of showing the mesh drawn. It seems only the topmost, combined draw call (in my case this is shown as "Draw 1" in the UI) will show a mesh in this UI (but it's only a tiny part of what is drawn). 

For comparison, in RenderDoc, when selecting any vkCmdDrawIndexed call, the mesh geometry will be displayed in RenderDoc's "Mesh Viewer".

Happy to share traces for both GAPID and RenderDoc to illustrate this, but github doesn't allow the files I have to be attached (too large).

**Comment by AWoloszyn** [comment]
So I expect the issue here is that our UI paradigm for Vulkan could be improved. (We are working on it).
A difference between GAPID and RenderDoc, in this instance is that GAPID shows the commands "as input by the application".

What this means in practice, is that I suspect the call you are clicking on is the "recording" of the vkCmdDrawIndexed.

If you want to find where it is executed, you can drill down into the VkQueueSubmit, and find the draw call nested under there. That will be the execution of the command in question.

![image](https://user-images.githubusercontent.com/9043212/60117275-c1b75300-9747-11e9-84ea-6e40e180a701.png)

Let me know if my suspicions are incorrect however. If there is a bug we should fix it.
I have opened 
https://github.com/google/gapid/issues/2877
to track the work needed to re-organize. We also have 
https://github.com/google/gapid/issues/2807
which documents the fact that we should update our docs to better reflect Vulkan usage.

**Comment by ronaldfw** [comment]
Yes, you are right. When I drill down into the vkQueueSubmit call, I can find all the render calls and actually see the geometry. So, it seems to be working as intended, but I agree with your suggestion that the UI can be improved here. 

Closing this issue as you have opened follow up issues to improve the UI / handling of the Vulkan command tree and documentation.
