### ISSUE TITLE
Scrolling the memory tab is not usable

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3029]
(spotted on Linux)
Try to vertically scroll in the memory tab leads to either:
- the scroll handle staying in the middle (if scroll action is slow)
- the scroll handle jumping to some other height (if scroll action is swift), but then jumping back to the middle when scrolling again

There is basically no good way to scroll quickly to an far away address.

**Comment by ben-clayton** [comment]
This is by design - the memory address range is enormous (0 to 2⁶⁴-1), making a 'real' scroll bar impossible to use.
The implementation allows you to perform local, relative scrolls. If you want to go to a significantly different address, use the jump-to-address feature or the drop down to jump to a memory observation.

Note: I believe this to be a fairly standard way to deal with enormous datasets. IIRC Visual Studio does something very similar with its memory view.
