### ISSUE TITLE
Possible to use gapii for arm linux target (non android) ?

### ISSUE THREAD

**Issue by eternity74** [google/gapid#303]
Hi.
I'd like to use this tool our env (non android, arm linux gles application)
I thought that I build libgapii.so and use LD_PRELOAD=libgapii.so for the gles application then use  gapit with local_port from ubuntu PC (local_port will forward to arm linux target device via ssh) to get trace. Does it make sense ?
If it makes sense, could anyone give a hint to me for building only gapii for embebed arm linux device ?
I am trying to build gapii under our env but it is hard to setup for me.
Thanks.

**Comment by ben-clayton** [comment]
Hello,

Yes, it should be possible, but it isn't something we have been testing so far. All of the symbols should be exposed in the generated `gles_exports.cpp` via the [`EXPORT` macro](https://github.com/google/gapid/blob/master/core/cc/target.h#L28).

The bit you're missing is the build steps to generate a `libgapii.so` for vanilla linux arm.

Android is handled a bit differently. It uses its own toolchain, and relies on [a different mechanism](https://github.com/google/gapid/blob/master/gapii/cc/android/installer.cpp) instead of `LD_PRELOAD` in order to hook into the calls.

We could certainly add the rules to the CMake build system to build an ARM set of libraries, however we are planning on switching to a different (and more reliable) build system soon. @ianthehat may be able to provide an ETA for this.
That said, if you wanted to brave the CMake rules, we'd happily accept a PR to generate this flavor of `libgapii.so` so long as it can be disabled with a flag.

If you're happy to wait, we can consider this a feature request, and we'll add support sometime after we've switched build systems.

Many thanks.

**Comment by eternity74** [comment]
Hi ben-clayton,
Thanks for your help.
I think there might be some conflict between x86 linux (GL) and  arm linux (GLES). I am not sure, I can make it work for both flavors. I will try to make libgapii.so with arm linux toolchain (GLES) by myself anyway.
If I have successful result, I will propose it to be accepted.
Also I'm interesting in new build system. Could you give some more information about it and ETA ?
Thanks a lot.

**Comment by ben-clayton** [comment]
> If I have successful result, I will propose it to be accepted.
Awesome, thank you.

The new build system is [bazel](https://bazel.build/). We're working to iron out some issues with Windows (the bazel team are still fixing some windows specific issues).
There are a number of benefits to bazel over what we currently have:
* It uses its own internal file system to keep track of dependencies. This removes the possibility of broken dependencies that cause flakey builds.
* It uses file content hashes instead of timestamps to determine touched files. This can greatly reduce the amount of work required for an incremental build.
* It has a built in vendoring system that can fetch (nearly) all the dependencies GAPID uses automatically.
* It's got far less legacy baggage than CMake.

@ianthehat may be able to give you an ETA.

Cheers,
Ben

**Comment by eternity74** [comment]
Dear Ben,

I made a pull request for this issue, could you take a look ?
https://github.com/google/gapid/pull/331

**Comment by AWoloszyn** [comment]
I just merged this pull-request. If there are any further issues please let us know!
