### ISSUE TITLE
Idea: Make JDWP package project independent ("go get"-able)

### ISSUE THREAD

**Issue by OmerYe** [google/gapid#3822]
Hello!

I reached this cool project as I was looking for a package to handle Java debugger wire protocol for my own project.

I assume I'm not the only one who would love using the package, maybe turning it into independent package could be a good idea?

By saying independent project I mean make it possible import it using `go get`, which is impossible not because it depends on `github.com/google/gapid/core/os/device`, which requires a generated protobuf structure.

**Comment by hevrard** [comment]
Hi @OmerYe,

This project is now in maintenance mode (see https://github.com/google/gapid#maintenance-mode) and we don't have the bandwidth to address this request.

Since GAPID is open-source, you may be able to reuse some of its code to create your own library, as long as you follow the Apache 2.0 license directives.

**Comment by OmerYe** [comment]
Ok thanks :)
