### ISSUE TITLE
Can GAPID capture the surface flinger?

### ISSUE THREAD

**Issue by dtoartist** [google/gapid#3863]
Hi,

I want to capture the GLES calls used by surface flinger. But I don't know how to capture the surface flinger (I tried the tools provided by GPU vendors, but still couldn't capture it). Is it a possible thing?

Thanks

**Comment by hevrard** [comment]
Hi,

This is not something that GAPID (or the more recent [AGI](https://github.com/google/agi)) can do, since Surface Flinger is operating after the app has produced a frame, see Figure 2 here:

https://source.android.com/devices/graphics#data-flow

In other words, tools like GAPID or AGI may monitor graphics API calls made by the app, but cannot insert themselves below Surface Flinger to monitor what it does.

Still, you can try AGI's system profiler to see Surface Flinger activity:

![screenshot](https://user-images.githubusercontent.com/6726747/121368111-bc527380-c932-11eb-94de-0d1322c1cd77.png)
