### ISSUE TITLE
glPushDebugGroupKHR is not handled correctly

### ISSUE THREAD

**Issue by ek9852** [google/gapid#459]
glPopDebugGroupKHR becomes the main item in the command tree (see the attached pic)
From the Log. gapir said attempted to call unsupported function glPopDebugGroupKHR/glPushDebugGroupKHR.

The message in glPushDebugGroupKHR/glPopDebugGroupKHR are not decoded.

And clicking on the glPopDebugGroupKHR item in the command tree trigger a redraw for framebuffer every-time even though there is no draw call for its children.

Log: https://drive.google.com/open?id=0B0S0_4EgiFmcTWFkN0FzR0RHUkE
Happen in applications that written by Unity.

<img width="1160" alt="screen shot 2017-05-30 at 2 42 08 pm" src="https://cloud.githubusercontent.com/assets/6452203/26606340/667eece6-4546-11e7-80ab-5f84d73dbabf.png">

**Comment by ben-clayton** [comment]
> glPopDebugGroupKHR becomes the main item in the command tree (see the attached pic)

This is a fallback string because the message is empty. I'll make a change so that there's a "User marker _N_" string in this case.

> From the Log. gapir said attempted to call unsupported function glPopDebugGroupKHR/glPushDebugGroupKHR.

I'll add a rule to our compatibility layer to disable debug markers for replay.

> The message in glPushDebugGroupKHR/glPopDebugGroupKHR are not decoded.

Now this is the interesting bit. [Based on the extension](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt), the caller should be passing a *negative* length if the string should be read until a null-terminator. It seems that Unity is passing 0, resulting in a zero-length string. I'll check their source to make sure this is a bug on their side, but we may have to fudge our code to support this broken case.

> And clicking on the glPopDebugGroupKHR item in the command tree trigger a redraw for framebuffer every-time even though there is no draw call for its children

Unfortunately this is WAI for now - the system does have the smarts right now to know that debug markers have no influence over the final image. This is something we can look to improve in the longer term.

**Comment by ek9852** [comment]
I am not sure there is a bug in Unity but shouldn't glPushDebugGroupKHR come first  in the command tree ?

**Comment by ben-clayton** [comment]
It does - it's just that a group with a zero-length string displays the name of the last command in the group.

**Comment by ben-clayton** [comment]
The remaining issue here is that it appears Unity is passing a 0 for the length parameter. I still need to check the source, and then decide whether we're going to fudge our systems to support this broken case, or whether we say this is WAI.

**Comment by dsrbecky** [comment]
Just for the record:

https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt

    The parameter <length> contains the number of characters in <message>. If 
    <length> is negative, it is implied that <message> contains a null 
    terminated string.

https://www.khronos.org/registry/OpenGL-Refpages/es3/html/glPushDebugGroup.xhtml

The parameter length contains the number of characters in message. If length is negative, it is implied that message contains a null terminated string.

**Comment by ben-clayton** [comment]
I've checked the Unity source and it was indeed broken until recently, and I expect the next release to contain this fix.

I guess we can add a fudge for now.

**Comment by ek9852** [comment]
Hack not working on Unity 5.2 on latest main truck 4d24ae5fa8b7e3cb9f78a8cdfdcfdf504e9710a4
![image](https://user-images.githubusercontent.com/6452203/27271519-0e8f66f8-547a-11e7-8837-18ab1e3d7c76.png)

**Comment by ben-clayton** [comment]
Humm, at least we're making the observation now. Reopening.
