### ISSUE TITLE
vkGetImageMemoryRequirements setting image size?!

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#460]
[This line seems highly suspicious.](https://github.com/google/gapid/blob/0497634e3f10aeb960c8386f1026d8b432685665/gapis/gfxapi/vulkan/vulkan.api#L3157) and is actually crashing in replay (maybe due to complications with DCE?)

**Comment by ben-clayton** [comment]
Removing the line causes the crash to move somewhere else. Seems like an image is null and the API isn't checking for nullptrs. Can give repro steps.

**Comment by AWoloszyn** [comment]
Investigating now.

**Comment by Qining** [comment]
The crash is caused by
1) vkGetImageMemoryRequirement is not handled.
2) image handle access in pipeline barrier is not handle.
Working on it

**Comment by ben-clayton** [comment]
What about [the line](https://github.com/google/gapid/blob/0497634e3f10aeb960c8386f1026d8b432685665/gapis/gfxapi/vulkan/vulkan.api#L3157) this bug title refers to?

**Comment by Qining** [comment]
I think it is correct that `vkGetImageMemoryRequirement` sets the image size. Actually this is the only place that the exact size of image can be obtained. The crash is because the creation of the image is removed (which should not, because eventually it is used in pipeline barrier), so Images[image] returns nil.

The problem is not revealed before is because, usually, an image will be used in some other commands in the command buffer. But the crashing trace does not contains any real use of the image, but a pipeline barrier. However, the trace is still valid, so we should handle the case.

**Comment by ben-clayton** [comment]
> I think it is correct that `vkGetImageMemoryRequirement` sets the image size.

Really? I don't see any mention of the state being changed [in the documentation](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkGetImageMemoryRequirements.html). The API is supposed to be a reflection of the driver state - the Vulkan driver doesn't set the size from the output parameter. It seems you're mixing API implementation with behaviors that make tracing easier.

**Comment by Qining** [comment]
Right, this is not a reflection of the driver state, it is let the state records the size of the image, like all the other records in the state. Like the when `vkBindBufferMemory` is called, we record the buffer is bound to a memory, so that later when processing the buffer, we know where to find the backing memory.

Like the other fields in the ImageObject, they are all recorded to ease the tracing. The API only works with the handle.

**Comment by dsrbecky** [comment]
Is it valid for application to never call this function?

**Comment by AWoloszyn** [comment]
This case is a bit awkward. I agree that that call does not modify state.

We use this in precisely one place, which is in `readCoherentMemoryInImage`.
What a user can do is call vkCreateImage, vkBindImageMemory(some coherent memory here).

When we have to read that coherent memory in the future, we have to know the size of the memory. Unfortunately the user, in their call to vkBindImageMemory() never specifies a size, only an offset, so this is the only way to get the actual number of bytes required by the driver.

That being said however, there is always the chance that the user never calls vkGetImageMemoryRequirements on a particular image,  and binds it "knowing" that the space will be sufficient. (e.g. 128x128 image in 1GB allocation, it will probably fit).

Furthermore modifying Coherent image memory is not valid unless the image is Linear.

**Comment by ben-clayton** [comment]
If you need additional metadata, then you should make additional queries at interception time and add it as extras to the atoms.
What you have right now will show up in the client as broken behavior - before and after the call to `vkGetImageMemoryRequirement` will have different values in the state view, meaning the debugger is lying to the user. Worse still, once we add the ability to see when variables were last changed, this will show up as a modification. I don't think this is acceptable.

**Comment by AWoloszyn** [comment]
As a follow-on to my last comment, we should be fine to remove this. The spec has this to say about images.

```
Host access to image memory is only well-defined for images created with
VK_IMAGE_TILING_LINEAR tiling and for image subresources of those
images which are currently in either the VK_IMAGE_LAYOUT_PREINITIALIZED
or VK_IMAGE_LAYOUT_GENERAL layout.
```

So we can either
* avoid doing coherent memory reads if the image is not linear
* assume all images are linear, and we can calculate the size from w*h*d

**Comment by Qining** [comment]
I agree we should remove this.

**Comment by AWoloszyn** [comment]
@dsrbecky As for you previous question, I do not think it is **TECHNICALLY** valid for an application to not call this. Looking at the spec it looks like even if you create 2 identical images, it is valid for the driver to return different values for `alignment` and `size`.

**Comment by AWoloszyn** [comment]
Fixed
