### ISSUE TITLE
Goto Api Call does not bring the command into view

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#485]
It gets very close though.... It is the first into out of view.

**Comment by pmuetschard** [comment]
The problem is this:
- when the tree is collpased, it neatly fits and no horizontal scroll bar is shown
- when you go to the command, the tree is expanded and the item is scrolled into view at the very bottom
- because the node has not been loaded yet, the UI sees it's text as "Loading...", which still neatly fits.
- then the node gets loaded, as well as it's nearby friends and now it no longer fits and the horizontal scrollbar is created
- the scrollbar is now obstructing the item

Solutions:
1- always show the horizontal scrollbar
2- investigate if there is some way to control the "reveal" when setting the selection to scroll a bit more than just the bare minimum.
3- maybe have some handler that is invoked when the scrollbar is shown that checks if it makes the selection disappear, and if so makes it re-appear
4- ?

**Comment by ben-clayton** [comment]
Appears to work on OSX. Assuming fixed, please reopen if you can repro otherwise.
