### ISSUE TITLE
replay.Custom does not have a thread ID

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#729]
This sounds like potentially very serious issue.
(in addition to the fact that it generates bindRenderer for every command in report)

**Comment by ben-clayton** [comment]
Good find. I seriously considered adding a thread ID to `Custom`, but decided that it was unlikely that you'd ever want to switch threads in the middle of some low-level logic. With that thought, I intended the `bindRendererOnContextSwitch` to be at the top of the transform chain, so that it would never see `Custom`s, but it ended up nearer the bottom.

With all that said, I'm not sure why it's creating a `BindRenderer` for every command in report? The logic only creates one if you switch to a thread with [a pre-existing context bound](https://github.com/google/gapid/blob/master/gapis/api/gles/replay.go#L357-L368). `Custom` has a thread ID of 0, which is unlikely to share a `eglMakeContext` or `eglMakeCurrent` call.

Any idea?

**Comment by dsrbecky** [comment]
the last statement is: t.context = GetContext(out.State(), thread)
so for replay.Custom: t.context = nil
find_issues will do glGetError after every command, so it effectively clears the context after each command.
I also believe there are cases where we do replay.Custom before the actual command

**Comment by ben-clayton** [comment]
Right, gotcha. I'll add an exception to `bindRendererOnContextSwitch` for `replay.Custom`. I assume that's preferable than passing even more thread IDs down?

**Comment by ben-clayton** [comment]
> I also believe there are cases where we do replay.Custom before the actual command

Oh right, I see where you're going with that. Fine, another sprinkling of IDs it is!

**Comment by dsrbecky** [comment]
Yeap... sorry to bear bad news.
