### ISSUE TITLE
Add gapis panic to log

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#754]
When gapis crashes, gapic shows helpful dialog box and says "see log for details".
Alas there no message in the log tab...

**Comment by pmuetschard** [comment]
Anything printed by gapis to stdout/stderr is added to the gapic log either as info (stdout) or warning (stderr). If you see the panic dialog, the panic must be in the log, since the the dialog recognizes the panics by looking at the logged messages.

I suggest checking gapic.log. The new version of the dialog has a hand link that will open the logging dir in the file browser.
