### ISSUE TITLE
Allow passing of additional flags to `am start` when tracing.

### ISSUE THREAD

**Issue by digish** [google/gapid#826]
Generally to debug dEQP android CTS graphics tests, we give command line options to the activity which select the testcase and other test parameters.

as the default activity launch will test the full package which will be very large.
so if option to give command line arguments while starting activity will help in such use cases.

example:
we start the dEQP application like below.

adb shell am start -n com.drawelements.deqp/android.app.NativeActivity -e cmdLine "'binaryname --deqp-watchdog=enable --deqp-log-filename=/sdcard/dEQP-Log.qpa  --deqp-gl-config-name=rgba8888d24s8ms0 --deqp-case=dEQP-GLES3.functional.fragment_ops.blend.fbo_srgb.equation_src_func_dst_func.add_constant_alpha_constant_alpha'"

**Comment by ben-clayton** [comment]
Great suggestion @digish.

**Comment by pmuetschard** [comment]
So, this appears to be very specific to dEQP. The parameter being passed to `am start` is `-e`, which is just passing along an [extra](https://developer.android.com/reference/android/content/Intent.html#getExtras()) along with the intent. The fact that `-e cmdline <stuff>` passes command line parameters is specific to dEQP.

Therefore, I think what we can do is provide an input field in the trace dialog "am start flags", which we then pass along. For this specific use case, you'd type in `-e cmdLine "..."`.

**Comment by ben-clayton** [comment]
I still think this is a useful feature to have. Re-opening.

**Comment by pmuetschard** [comment]
Yes, sorry for the confusion. I didn't mean to give the impression that we shouldn't do it, just that it will be more general than "command line arguments", since it's really just an activity extra in dEQP that is used to simulate cli args. That's why I changed the title to be more general.

I was and am still planing on doing this, though I could use a suggestion of what to label the text field, please...

**Comment by y-novikov** [comment]
This is also needed for running Chromium tests, to the extent that the tests crash if intent extras are not provided.
Can this please get a higher priority?

Suggestion for text field label: "Intent Arguments".
From https://developer.android.com/studio/command-line/adb.html#IntentSpec

**Comment by null77** [comment]
+1 to increasing priority for this feature for running ANGLE/Chromium tests.

**Comment by AWoloszyn** [comment]
I just put up a MR for part of this, once it passes the bots, I will merge.
Once it has merged you should be able to trace with the command-line tool and add additional args.

`gapit trace -android-additionalargs "additional flags to am start go here" app_to_trace`

Since the additional flags already must be quoted, be sure to escape inner quotes.

**Comment by ttgdz** [comment]
when does this feature added in the release version?

**Comment by ben-clayton** [comment]
We're still ironing out a few last issues that is preventing us from pushing another release (we've switch build systems, which has had a number of knock-on effects).

I estimate GAPID v1.1.0 will be released late next week. If you require a build before then, I can make you a custom build.

**Comment by null77** [comment]
Thanks for fixing this issue!

**Comment by digish** [comment]
Thank you for adding this feature.
It will be helpful.
